version: "3"

x-uffizzi:
  ingress:
    service: ibex
    port: 7681
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true
services:
  
  ibex:
    build:
      context: .
      dockerfile: ./Dockerfile.uffizzi
    ports:
    - "7700:7700"
    - "7681:7681"
    volumes:
      - ./:/ibex-core
    entrypoint: ["/bin/bash"] 
    command: 
    - "-c"  
    - "
        cd ibex-core && \
        ttyd bash
      "
    # entrypoint: ["/bin/bash"] 
    # command: 
    # - "-c"
    # - "apt-get update && \ 
    #   apt-get install neovim -y && \
    #   apt-get install unzip -y && \ 
    #   apt-get install wget -y && \
    #   wget 'https://github.com/$GHA_ACTOR/$GHA_REPO/archive/refs/heads/$GHA_BRANCH.zip' && \
    #   unzip $GHA_BRANCH.zip -d . && \
    #   rm -rf $GHA_BRANCH.zip && \
    #   export RISCV=/tools/riscv/ && \
    #   wget 'https://github.com/lowRISC/riscv-isa-sim/archive/refs/tags/ibex-cosim-v0.3.zip' && \
    #   unzip ibex-cosim-v0.3.zip && \
    #   rm -rf ibex-cosim-v0.3.zip && \
    #   git clone https://github.com/riscv/riscv-pk && \
    #   apt-get install device-tree-compiler -y && \
    #   cd $GHA_REPO-$GHA_BRANCH && \
    #   ttyd bash
    #   "
    deploy:
      resources:
        limits:
          memory: 4000M
